### ISSUE TITLE
Add Data from another country

### ISSUE THREAD

**Issue by Jorghe** [OpenBeta/climbing-data#11]
Is there a way to expand this set of data to another country?

I know many of the developers in the north part of Mexico, is there a way I can provide you the beta for further expansion?

**Comment by vnugent** [comment]
We welcome new datasets.  Just make sure they're compatible with our license, [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/).

Ways you can share new climbs with us:
1.  Submit data files in machine-readable formats such as JSON, CSV, etc
2. Coming soon:  you can add new climbs to our database: https://github.com/OpenBeta/open-tacos/issues/496

**Comment by vnugent** [comment]
Hi @Jorghe,
you can now add new areas for Mexico.

FAQ: https://openbeta.substack.com/p/hackathon-2022
