### ISSUE TITLE
Do you have permission to use MountainProject data?

### ISSUE THREAD

**Issue by jorroll** [OpenBeta/climbing-data#6]
Hi, I'm interested in using this dataset for a hobby project, but it's unclear if you (the maintainers of this dataset) actually have permission to use it. Has ADVENTURE PROJECTS, INC given you (the maintainers) permission to use and distribute this MountainProject dataset under a CC BY SA 4.0 license?

**Comment by vnugent** [comment]
I don't believe ADVENTURE PROJECTS owns copyright to contents or "betas" created by climbers.

**Comment by jorroll** [comment]
(a) even if that were true, the users themselves would certainly own their uploaded content, so I think you'd still need permission from individual users to redistribute their content.

(b) did you read the MountainProject [Terms of Service](https://www.adventureprojects.net/ap-terms)? To my reading, it's pretty clear that users of mountainproject.com maintain ownership of their data but they provide a wide ranging license to mountainproject.com to use that data. MountainProject could give you, or anyone else, permission to redistribute that data. But I don't think you can do that without their permission. Separately, individual users could give you, or anyone else, permission to redistribute that data, but you'd need to get that permission from each individual user of mountainproject.com.

Of course, I'm no lawyer and, for the record, I don't have any affiliation with mountainproject.com or ADVENTURE PROJECTS, INC. I'd certainly like to be able to use this dataset and I really like the goal of this repo (i.e. creating an open source rock climbing dataset), but I think you need to get permission from _somebody_ to redistribute this data.

**Comment by jorroll** [comment]
I'm also skeptical that MountainProject.com would allow a 3rd party to redistribute their data with a more permissive license than they themselves provide.

**Comment by vnugent** [comment]
Yes, I have read their ToS.  It's written to protect their interests, not for the benefit of the climbing community.  I appreciate that you brought this up.  If you really care about having open access to climbing data, I encourage you to voice your opinions under my Open letter thread on their forum.

**Comment by vnugent** [comment]
@jorroll As you know the repo was taken offline for over 2 months due to an improper DMCA by OnXmaps/ADVENTURE PROJECTS.  We submitted a counter-notice and GitHub has reversed the takedown.  

If you feel their copyright claim hinders your hobby project or a similar effort by community members, I'd suggest you bring up the matter to them.

**Comment by jorroll** [comment]
@vnugent I decided to use OpenStreetMap's rock climbing data. While that dataset isn't quite as large as MountainProject, it is still quite large and more than adequate for my purposes.
